### ISSUE TITLE
Bug: handling files from global visibility

### ISSUE THREAD

**Issue by 6elkir** [yiisoft/classifier#18]
### What steps will reproduce the problem?
scanFiles finds files only in the specified directory, everything is ok.

### What is the expected result?
However, get_declared_classes processes ALL classes in the context's reach. This means that if we want to get a list of classes from a given directory, but there are other classes in the project that implement the given interface, the find method will return them as well.

### What do you get instead?
I recommend filtering the directory at the class reflection level

**Comment by xepozz** [comment]
Thanks for the suggestion. Could you please provide a test case? I've made a fix, but the test case is needed.

**Comment by vjik** [comment]
It seems the idea is to search for any declared class, not by directory only. But `get_declared_class()` returns loaded classes only, we can't get all classes without first loading them. This means that you need to search the directory always.

**Comment by vjik** [comment]
> Thanks for the suggestion. Could you please provide a test case? I've made a fix, but the test case is needed.

For example, create class `TestUser` out of `tests` directory:

```php
<?php

declare(strict_types=1);

namespace Yiisoft\Classifier;

use Yiisoft\Classifier\Tests\Support\Interfaces\UserInterface;

final class TestUser implements UserInterface
{
}
```

And add `new TestUser();` before run `Classifier` in tests. It's will broke tests, because `TestUser` will be found also.
